name: 'Setting context for Alibaba Cloud Container Service for Kubernetes (ACK)'
description: 'Log in to a container registry'
inputs: 
  access-key-id:
    description: 'Access key id for Alibaba Cloud'
    required: true
  access-key-secret:
    description: 'Access key secret for Alibaba Cloud'
    required: true
  cluster-id:
    description: 'Kubernetes cluster id'
    required: true
branding:
  color: 'orange'
  icon: 'compass'
runs:
  using: 'node12'
  main: 'dist/index.js'
